#!/bin/bash

function install_package() {
  name=$1
  version=$2
  curl -LO ${SWIFT_URL}/package/$name-$version.tgz
  mkdir -p /app/vendor/$name
  tar -xv -C /app/vendor/$name -f $name-$version.tgz
}

function validate_env() {
  if [ -z "$SWIFT_BUCKET" ]; then
      echo "Must set SWIFT_BUCKET environment variable" >&2
      exit 1
  fi
}

function mktmpdir() {
  tempdir="$( mktemp -t $1_XXXX )"
  rm -rf $tempdir
  mkdir -p $tempdir
  echo $tempdir
}

function md5() {
  md5sum $1 | awk '{print $1}'
}
